name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          # Strawberry Perl is pre-installed on windows-latest runner and required for bundled-sqlcipher-vendored-openssl
          # We don't need to manually install OpenSSL because we are using 'vendored-openssl' feature which builds it from source using Perl.
          perl --version
          
          # Remove any potential conflicting environment variables if they exist
          Remove-Item Env:\OPENSSL_DIR -ErrorAction SilentlyContinue
          Remove-Item Env:\OPENSSL_LIB_DIR -ErrorAction SilentlyContinue
          Remove-Item Env:\OPENSSL_INCLUDE_DIR -ErrorAction SilentlyContinue

      - name: install frontend dependencies
        run: pnpm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        id: tauri_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      # Step to build and upload Portable version (only for Windows)
      - name: Build Portable Version (Windows)
        if: matrix.platform == 'windows-latest'
        shell: powershell
        run: |
          pnpm portable
          Compress-Archive -Path PasswordMan-Portable -DestinationPath PasswordMan-Portable.zip

      - name: Upload Portable Version (Windows)
        if: matrix.platform == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: PasswordMan-Portable.zip
          tag_name: ${{ github.ref_name }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
